name: cicd
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compile Java Program
      run: javac HelloWorld.Java

    - name: Run Java Program
      run: java HelloWorld
